--
-- PostgreSQL database dump
--

\restrict quQg7b1iXyazVXjM4t8fJOP4wZlidC9tF8VfvyIqmXu6Fatj2NqgEVKf3v8nfuX

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

-- Started on 2026-03-06 14:20:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16612)
-- Name: rd_account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rd_account (
    rid bigint NOT NULL,
    active boolean NOT NULL,
    address character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    dob date NOT NULL,
    gender character varying(255) NOT NULL,
    mobile character varying(255) NOT NULL,
    occupation character varying(255) NOT NULL,
    pan_no character varying(255) NOT NULL,
    rd_amount numeric(38,2) NOT NULL,
    rd_start_date date NOT NULL,
    user_id bigint NOT NULL,
    closed_date date,
    closure_type character varying(255),
    payout_amount numeric(38,2),
    last_maturity_payout numeric(38,2),
    last_payout_date date
);


ALTER TABLE public.rd_account OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16611)
-- Name: rd_account_rid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rd_account ALTER COLUMN rid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rd_account_rid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16627)
-- Name: rd_transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rd_transaction (
    tid bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone,
    payment_mode character varying(255),
    penalty_amount numeric(38,2) NOT NULL,
    rd_account_id bigint NOT NULL,
    reference_id character varying(255),
    status character varying(255) NOT NULL,
    transaction_date date NOT NULL,
    transaction_month integer NOT NULL,
    transaction_year integer NOT NULL,
    CONSTRAINT rd_transaction_payment_mode_check CHECK (((payment_mode)::text = ANY ((ARRAY['CASH'::character varying, 'UPI'::character varying])::text[]))),
    CONSTRAINT rd_transaction_status_check CHECK (((status)::text = ANY ((ARRAY['SUCCESS'::character varying, 'FAILED'::character varying, 'PENALTY'::character varying])::text[])))
);


ALTER TABLE public.rd_transaction OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16626)
-- Name: rd_transaction_tid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rd_transaction ALTER COLUMN tid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rd_transaction_tid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16602)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    acno character varying(20) NOT NULL,
    adharno character varying(12) NOT NULL,
    city character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    fullname character varying(255) NOT NULL,
    terms_accepted boolean NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16601)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4759 (class 2606 OID 16618)
-- Name: rd_account rd_account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rd_account
    ADD CONSTRAINT rd_account_pkey PRIMARY KEY (rid);


--
-- TOC entry 4765 (class 2606 OID 16635)
-- Name: rd_transaction rd_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rd_transaction
    ADD CONSTRAINT rd_transaction_pkey PRIMARY KEY (tid);


--
-- TOC entry 4755 (class 2606 OID 16610)
-- Name: users uk8vyxy7fxbmkuw8444ua6wwmji; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk8vyxy7fxbmkuw8444ua6wwmji UNIQUE (adharno);


--
-- TOC entry 4767 (class 2606 OID 16637)
-- Name: rd_transaction ukgeh0eeqjpaeww6bupcrf3pmae; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rd_transaction
    ADD CONSTRAINT ukgeh0eeqjpaeww6bupcrf3pmae UNIQUE (rd_account_id, transaction_month, transaction_year);


--
-- TOC entry 4761 (class 2606 OID 16620)
-- Name: rd_account uklpusjvvuxlqfcv4obx78gaw2m; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rd_account
    ADD CONSTRAINT uklpusjvvuxlqfcv4obx78gaw2m UNIQUE (user_id);


--
-- TOC entry 4757 (class 2606 OID 16608)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4762 (class 1259 OID 16638)
-- Name: idx_rd_tx_account; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_rd_tx_account ON public.rd_transaction USING btree (rd_account_id);


--
-- TOC entry 4763 (class 1259 OID 16639)
-- Name: idx_rd_tx_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_rd_tx_status ON public.rd_transaction USING btree (status);


--
-- TOC entry 4768 (class 2606 OID 16621)
-- Name: rd_account fk_rd_account_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rd_account
    ADD CONSTRAINT fk_rd_account_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);


-- Completed on 2026-03-06 14:20:35

--
-- PostgreSQL database dump complete
--

\unrestrict quQg7b1iXyazVXjM4t8fJOP4wZlidC9tF8VfvyIqmXu6Fatj2NqgEVKf3v8nfuX

